name:                pacman
version:             0.1.0.0
github:              "jonathanychen/pacman-pfp"
license:             BSD-3-Clause
author:              "Jonathan Chen, Kevin Wang"
maintainer:          "jyc2183@columbia.edu, kjw2169@columbia.edu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pacman#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- parallel
- deepseq
- vector
- mtl
- gloss

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  pacman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman

tests:
  pacman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman
    - hspec
